### ISSUE TITLE
Package.json's exports field causes issues

### ISSUE THREAD

**Issue by martpie** [martpie/next-transpile-modules#147]
- https://github.com/martpie/next-transpile-modules/issues/139#issuecomment-742637650
- https://github.com/martpie/next-transpile-modules/issues/139#issue-754123730
- #139 

Is there something wrong with `enhanced-resolve` and it cannot detect ESM via `exports`?

**Comment by simlrh** [comment]
Same issue with `dequal` package - I'm working around it by adding `exportsFields: []` to the `enhanced-resolve` config.

**Comment by martpie** [comment]
Well that's interesting, but kinda defeat the purpose of exports fields 🤔

**Comment by martpie** [comment]
I just tried with `nanoid`, everything seems to be working fine 🤔 `exports` field is well respected

**Comment by Algram** [comment]
@martpie it does not seem fixed on our end. The two packages we have problems with are `dequal` and `nanoid`.
With `next-transpile-modules:6.2.0` and `next:10.0.6` we get the following error when transpiling:

![image](https://user-images.githubusercontent.com/5053729/106863136-5fb32380-66c8-11eb-95a3-433b9d47ee65.png)

Is there a quick workaround for this issue specifically?

Thanks for your time!

**Comment by andrekorolev** [comment]
I have the same problem with the same packages and versions.

`nanoid:3.1.20` package.json: 
`
"exports": {
    ".": {
      "browser": {
        "development": "./index.dev.js",
        "production": "./index.prod.js"
      },
      "require": "./index.cjs",
      "import": "./index.js",
      "types": "./index.d.ts"
    },
    "./package.json": "./package.json",
    "./async/package.json": "./async/package.json",
    "./async": {
      "browser": "./async/index.browser.js",
      "require": "./async/index.cjs",
      "import": "./async/index.js"
    },
    "./non-secure/package.json": "./non-secure/package.json",
    "./non-secure": {
      "require": "./non-secure/index.cjs",
      "import": "./non-secure/index.js"
    },
    "./url-alphabet/package.json": "./url-alphabet/package.json",
    "./url-alphabet": {
      "require": "./url-alphabet/index.cjs",
      "import": "./url-alphabet/index.js"
    },
    "./index.d.ts": "./index.d.ts"
  }
`

@martpie with what versions did you have it work?

**Comment by andrekorolev** [comment]
nothing special
I added nanoid in my next.config.js:
`const withTM = require('next-transpile-modules')(['nanoid']);`
and when I run build I see:
`
Error: next-transpile-modules - an unexpected error happened when trying to resolve "nanoid"
Error: Package path . is not exported from package /Users/z/a/b/c/node_modules/nanoid (see exports field in /Users/z/a/b/c/node_modules/nanoid/package.json)
    at getPackageRootDirectory (/Users/z/a/b/c/node_modules/next-transpile-modules/src/next-transpile-modules.js:83:11)
`

Next - 10.0.6
NTM - 6.2.0
nanoid - 3.1.20
yarn - 1.22.10
node - 14.15.4

**Comment by martpie** [comment]
The problem seems to be coming from upstream and `enhanced-resolve`

**Comment by Algram** [comment]
@martpie Thanks a lot for investigating! In the meantime, is there any short term fix my team can apply? Otherwise we would have to wait for the maintainers of `dequal` and `nanoid`.

**Comment by daphnesmit** [comment]
This probably has to do with NPM 7?

**Comment by martpie** [comment]
no, nothing to do with `npm`. I have a fix on `master` (that I don't understand, but it works). I would like to finish a couple of other things and then I will trigger a release.

**Comment by martpie** [comment]
Can anyone confirm me it's fixed in `6.3.0`?

**Comment by andrekorolev** [comment]
it works now, no error during compilation in console. 
Although app is not opened in IE =D but it seems to be a local problem
@martpie thanks for quick fix

**Comment by Algram** [comment]
@martpie @andrekorolev it does unfortunately not fix the underlying problem: `nanoid` and `dequal` still do not get transpiled. The difference now is that the build succeeds though. Once you open the app in IE11, javascript breaks the page since IE can not parse arrow functions and const statements that are now in the bundle (from `nanoid` and `dequal`).

**Comment by martpie** [comment]
Can you output here the debug log? (see README)

**Comment by Algram** [comment]
@martpie sure, here you go:

```
next-transpile-modules - WARNING experimental Webpack 5 support enabled
next-transpile-modules - the following paths will get transpiled:
  - /home/username/dev/shop/node_modules/clean-stack
  - /home/username/dev/shop/node_modules/crypto-hash
  - /home/username/dev/shop/node_modules/dequal
  - /home/username/dev/shop/node_modules/escape-string-regexp
  - /home/username/dev/shop/node_modules/is-plain-obj
  - /home/username/dev/shop/node_modules/nanoid
  - /home/username/dev/shop/node_modules/query-string
  - /home/username/dev/shop/node_modules/recoil
  - /home/username/dev/shop/node_modules/split-on-first
  - /home/username/dev/shop/node_modules/strict-uri-encode
  - /home/username/dev/shop/node_modules/yn
info  - Using external babel configuration from /home/username/dev/shop/babel.config.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/strict-uri-encode/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/split-on-first/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/nanoid/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/lenient.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/crypto-hash/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/nanoid/url-alphabet/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/crypto-hash/browser.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/nanoid/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/lenient.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/
recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/cjs/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/yn/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/dequal/dist/index.mjs
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/nanoid/index.browser.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/nanoid/index.browser.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/nanoid/url-alphabet/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/recoil/es/recoil.js
info  - Creating an optimized production build ...next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/strict-uri-encode/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/split-on-first/index.js
next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/is-plain-obj/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /home/username/dev/shop/node_modules/query-string/index.js
(node:17755) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Creating an optimized production build  
warn  - Compiled with warnings
```

**Comment by martpie** [comment]
Well, when I do a `yarn create next-app`, the default app does not even run on IE11, so I assume this is a problem on Next.js side. The nanoid files **are** getting transpiled it appears

**Comment by martpie** [comment]
Still testing a few things on my side.

**Comment by martpie** [comment]
Working fine on my side, check your next config or your `nanoid` implementation.

![Screenshot 2021-02-08 173313](https://user-images.githubusercontent.com/1311607/107249559-c5d6d800-6a33-11eb-8fb8-18e466ba02e4.png)
n.

**Comment by Algram** [comment]
@martpie I am sorry to bother you again, but your example will work of course, since the page you show in the screenshot is rendered on the server. Have you actually checked if the client side hydration works in your example?

Basically what happens if you call `nanoid()` on the client?

**Comment by martpie** [comment]
The page is re-hydrated on the browser (which causes a mismatch because nanoid will generate another string).

So yeah, nanoid is called on the browser as well.

**Comment by Algram** [comment]
Hi @martpie,

after some more digging and debugging, we have found the offending package. It is `clean-stack`. This is not getting transpiled by `next-transpile-modules` now, but was before.

Could you maybe take the time and verify that?

Thanks so much!

**Comment by martpie** [comment]
This is not `next-transpile-modules`'s job to transpile the dependencies of the dependencies you try to transpile. If you use:

```tsx
 const withTM = require('next-transpile-modules')(['nanoid']);
```

only `nanoid` will be transpiled. Not the dependencies of `nanoid`. 

So you'd need to manually add `clean-stack` to the list (or open an issue on its repo).

**Comment by Algram** [comment]
@martpie  Sorry, forgot to mention, that I DO have `clean-stack` in the config:
![image](https://user-images.githubusercontent.com/5053729/108727119-7fe83c80-7528-11eb-91b1-fe9a80b3f32f.png)

Still it does not get transpiled.

**Comment by martpie** [comment]
Can you paste here the content of `clean-stack`'s `package.json`, and a screenshot of the package file structure in `node_module`?

**Comment by Algram** [comment]
@martpie Sure, here you go:
![image](https://user-images.githubusercontent.com/5053729/108740406-ed4e9a00-7535-11eb-9254-e5f8e18b9007.png)

![image](https://user-images.githubusercontent.com/5053729/108740456-fa6b8900-7535-11eb-8f00-29b675dbd6be.png)

**Comment by martpie** [comment]
thanks, so I believe `next-transpile-modules` modules resolver may not be looking for `index.js` as a default file for modules. I'll have a look at it when I can.

**Comment by martpie** [comment]
@Algram can you open a separate issue with a reproduction/piece of code that should be working but is not, etc?

So we avoid polluting this thread.
